name: Run Behave Tests & Generate Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    name: Run Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use system Python
        run: |
          python3 --version
          pip3 --version

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache Allure binary
        id: cache-allure
        uses: actions/cache@v3
        with:
          path: /opt/allure
          key: allure-${{ runner.os }}-2.24.1

      - name: Install Allure if not cached
        if: steps.cache-allure.outputs.cache-hit != 'true'
        run: |
          curl -L https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz | tar -xz -C /opt/
          mv /opt/allure-2.24.1 /opt/allure

      - name: Run Behave Tests
        run: |
          source venv/bin/activate
          behave --no-capture --no-capture-stderr --format allure_behave.formatter:AllureFormatter --outfile=allure-results

      - name: Generate Allure Report
        run: |
          source venv/bin/activate
          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
            /opt/allure/bin/allure generate allure-results --clean -o allure-report
          else
            mkdir -p allure-report && echo "<html><body><h1>No test results found</h1></body></html>" > allure-report/index.html
          fi

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy Allure Report to GitHub Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

  comment-pr:
    needs: deploy
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR with Allure Report URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const allureURL = "https://diwakarrana1.github.io/BehaveFramework/";
            const body = `✅ Allure Report is available here: [Allure Report](${allureURL})`;
            github.rest.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
